# linear_model

## LogisticRegressor
1. 首先是分类模式 multi_class 参数
    1. 默认为ovr，使用的是sigmoid函数+熵作为损失函数
    2. 如果使用multinomial [mvm]，使用的是softmax函数+交叉熵作为损失函数
2. 其次是梯度求解方法 solver
    1. liblinear 默认
    2. lbfgs
    3. newton-cg
    4. sag
    5. saga
3. 更精细化的参数
    1. 最大迭代次数 max_iter
    2. 最小损失值 tol
    3. 正则化系数 $C=\frac{1}{\lambda}$
    4. 正则化方式 penalty 有两个可选参数 l1 l2

# polynomial_model

## 线性升维
sklearn.preprocessing PolynomialFeatures

In [3]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [6]:
x_in = np.arange(2,12,1).reshape(5,2)
print(x_in)

[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [12]:
# 没有平方项
poly_1 = PolynomialFeatures(degree=2, interaction_only=True)
poly_1_out = poly_1.fit_transform(x_in)
print(poly_1_out)
print(poly_1.n_input_features_, poly_1.n_output_features_)

[[  1.   2.   3.   6.]
 [  1.   4.   5.  20.]
 [  1.   6.   7.  42.]
 [  1.   8.   9.  72.]
 [  1.  10.  11. 110.]]
2 4


In [13]:
# 没有平方项，没有常数项
poly_2 = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
poly_2_out = poly_2.fit_transform(x_in)
print(poly_2_out)
print(poly_2.n_input_features_, poly_2.n_output_features_)

[[  2.   3.   6.]
 [  4.   5.  20.]
 [  6.   7.  42.]
 [  8.   9.  72.]
 [ 10.  11. 110.]]
2 3


In [14]:
# 全部项
poly_3 = PolynomialFeatures(degree=2, interaction_only=False, include_bias=True)
poly_3_out = poly_3.fit_transform(x_in)
print(poly_3_out)
print(poly_3.powers_)

[[  1.   2.   3.   4.   6.   9.]
 [  1.   4.   5.  16.  20.  25.]
 [  1.   6.   7.  36.  42.  49.]
 [  1.   8.   9.  64.  72.  81.]
 [  1.  10.  11. 100. 110. 121.]]
[[0 0]
 [1 0]
 [0 1]
 [2 0]
 [1 1]
 [0 2]]
