<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#从文件导入" data-toc-modified-id="从文件导入-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>从文件导入</a></span></li><li><span><a href="#从外部导入" data-toc-modified-id="从外部导入-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>从外部导入</a></span></li></ul></div>

In [22]:
import numpy as np
import random

# 从文件导入

In [24]:
data=np.loadtxt("./archive/USvideo_data.csv",delimiter=',',dtype="int32",skiprows=1,usecols=(0,1,2,3),max_rows=10000)
data.shape

(7997, 4)

In [7]:
print(data[2])

[5845909  576597   39774  170708]


In [13]:
print(data[2:])

[[5845909  576597   39774  170708]
 [2642103   24975    4542   12829]
 [1168130   96666     568    6666]
 ...
 [ 142908    7088      68     437]
 [  24532    2148      77       0]
 [ 144039    1574      59       0]]


In [14]:
print(data[:,2])

[ 5931 26679 39774 ...    68    77    59]


In [15]:
print(data[:,[2,3]])

[[  5931  46245]
 [ 26679      0]
 [ 39774 170708]
 ...
 [    68    437]
 [    77      0]
 [    59      0]]


In [26]:
 data.sum(axis=1)

array([4766258, 8072651, 6632988, ...,  150501,   26757,  145672])

In [28]:
data.sum(axis=0)

array([7510332161,  276001267,   14243015,   36857239])

In [32]:
t1=np.arange(12).reshape((3,4)).astype("float32")
print(t1)
t1[1,2:]=np.nan
print(t1)
# 方法：将nan替换为本列均值
for i in range(t1.shape[1 ])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 0.  1.  2.  3.]
 [ 4.  5. nan nan]
 [ 8.  9. 10. 11.]]


# 从外部导入

In [11]:
str = 'abcdef'
str_array = np.fromstring(str,dtype=np.int8)
print(str_array)

[ 97  98  99 100 101 102]


/var/folders/zh/fmxxp3g1653ccyjmyp5z3bc00000gn/T/ipykernel_89829/2888418160.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  str_array = np.fromstring(str,dtype=np.int8)


In [13]:
def func(x,y):
    return x*y
func_array = np.fromfunction(func,(4,5))
print(func_array)

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  2.  4.  6.  8.]
 [ 0.  3.  6.  9. 12.]]


In [21]:
test = np.arange(20).reshape([4,5])
print(test)
print(test[0,:])
print(np.sum(test,axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[0 1 2 3 4]
[30 34 38 42 46]


In [26]:
s = np.arange(10)
t = s.reshape([-1,1])
t.shape
s.shape

(10,)