In [2]:
import numpy as np
import random
from matplotlib import pyplot as plt
import random

In [9]:
t1 = np.array([1,2,3,4,5])
t2 = np.array(range(1,6,2))
t3 = np.arange(4,10,2)
print(type(t1))
print(type(t2))
print(t3)
print(type(t3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[4 6 8]
<class 'numpy.ndarray'>


In [13]:
a = np.arange(2,10,4)
print(a.dtype)

int64


In [17]:
t4=np.array(range(1,4),dtype="i1")
t4.dtype

dtype('int8')

In [18]:
t5=np.array([1,1,0,1,0,0],dtype=bool)
t5.dtype

dtype('bool')

In [21]:
t6 = t5.astype("i1")
print(t6.dtype)
print(t5.dtype)

int8
bool


In [24]:
random.random() 

0.9029739844839472

In [26]:
t7 = np.array([random.random() for i in range(10)])
t8 = np.round(t7)
print(t7)
print(t8)

[0.36387214 0.85284083 0.52799382 0.69158611 0.51262803 0.94926227
 0.73970601 0.78675353 0.04589219 0.27134793]
[0. 1. 1. 1. 1. 1. 1. 1. 0. 0.]


In [37]:
t9=np.arange(12)
print(t9.shape)
t10=t9.reshape((3,4))
print(t10.shape)
t11=t10.reshape((12,))
print(t11)
t12=t10.reshape((12,1))
print(t12)
t13=t10.reshape((1,12))
print(t13)
t14=t10.flatten()
print(t14)

(12,)
(3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
